### ISSUE TITLE
General Quality Control

### ISSUE THREAD

**Issue by camwebb** [camwebb/ALA-informatics#28]
This is an umbrella task issue for noting questions and discrepancies that may be moved to separate issues later. Please tick the item if resolved. If starting a new issue, please cite this issue #.

The first batch were raised in an email from Steffi today:

- [ ] Anderson collection - accessioned with ALAAC?  Since most of the Anderson specimens are kept separate in folders in the range, we should go through them one by one and make sure all have ALAAC accession numbers on the sheet and in Arctos.
- [ ] Agricultural Experimental Station (AES) - accessioned with ALAAC?
- [ ] Were some NPS shipments assigned ALAAC numbers in advance?
- [ ] https://arctos.database.museum/guid/UAM:Herb:98512 The DNG and jpg are of Saxifraga, HTML link to Morphbank with images is to Bromus?
- [ ] https://arctos.database.museum/guid/UAMb:Herb:10506 Two collecting events: the Kukpuk river one and the correct one?
- [ ] https://arctos.database.museum/guid/UAMb:Herb:11766 this is the same with two events, as above
- [ ] USFS/TFNS herbarium: we have received large chunks (if not all of these). Some of them have the USFS number entered in Arctos others do not. We need to make sure going forward this is consistently implemented. There are lots of these in the backlog, and most will have digital metadata.

**Comment by camwebb** [comment]
The 'USFS/TFNS herbarium' issue above is now two separate issues: #30 and #29
